home/urls.py
from django.conf.urls import url
from home import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

]

moau2/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from home import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', views.index, name = 'index'),
    url('', include('social_django.urls', namespace='social')),
    url(r'^home/', include('home.urls',  namespace='home')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^bookmarket/', include('bookmarket.urls', namespace='bookmarket')),
    url(r'^groupbuying/', include('groupbuying.urls', namespace='groupbuying')),
    url(r'^taxipool/', include('taxipool.urls', namespace='taxipool')),
    url(r'^mypage/', include('mypage.urls', namespace='mypage')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
   

mypage/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.changeinfo, name="changeinfo"),
    url(r'^mp_bookmarket', views.mp_bookmarket, name="mp_bookmarket"),
    url(r'^mp_groupbuying/$', views.mp_groupbuying, name="mp_groupbuying"),
    url(r'^mp_taxipool/$', views.mp_taxipool, name="mp_taxipool"),

    url(r'^bid_detail/$', views.bid_detail, name="bid_detail"),
    url(r'^register_detail/$', views.register_detail, name="register_detail"),

    url(r'^attend_detail/$', views.attend_detail, name="attend_detail"),
    url(r'^seek_detail$', views.seek_detail, name="seek_detail"),

    url(r'^apply_detail/$', views.apply_detail, name="apply_detail"),
    url(r'^open_detail/$', views.open_detail, name="open_detail"),
    # url(r'^backout/$', views.backout, name="backout"),
    # url(r'^bookmarket/$', views.bookmarket, name="bookmarket"),
    # url(r'^groupbuying/$', views.groupbuying, name="groupbuying"),
    # url(r'^taxipool/$', views.taxipool, name="taxipool"),

]

mypage/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.

mypage/forms.py
from django.forms import ModelForm
from .models import  Product_nickname_HP

class Nickname_HP_Form(ModelForm):
    class Meta:
        model = Product_nickname_HP
        fields = ['nickname', 'HP']

mypage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from bookmarket.models import *
from groupbuying.models import *
from taxipool.models import *
from django.contrib.auth.decorators import login_required
from django.db import connection, transaction
from home.views import * # common fucntion

import datetime
# Create your views here.

def changeinfo(request):
    return render(request, 'mypage/changeinfo.html')

def mp_bookmarket(request):
    cursor = connection.cursor()
    context = get_entire_bookmarket_with_user(request, cursor, True)
    return render(request, 'mypage/bookmarket.html', context)

def mp_groupbuying(request):
    cursor = connection.cursor()
    context = get_entire_groupbuying_with_user(request, cursor, True)
    return render(request, 'mypage/groupbuying.html',context)

def mp_taxipool(request):
    cursor = connection.cursor()
    context = get_entire_taxipool_with_user(request, cursor, True)
    return render(request, 'mypage/taxipool.html',context)

def bid_detail(request):
    new_bid_price = request.POST['new_bid_price1']
    bid_id = request.POST['bid_id']
    product_id = request.POST['product_id']

    cursor = connection.cursor()
    if request.POST.get('new_bid'):
        update_bid(request, cursor, bid_id, new_bid_price)

    if request.POST.get('delete'):
        delete_bid(request, cursor, bid_id)

    # common
    context = get_entire_bookmarket_with_user(request, cursor, True)
    return render(request, 'mypage/bookmarket.html', context)

def register_detail(request):
    product_id = request.POST['product_id']

    cursor = connection.cursor()
    if request.POST.get('closing'):
        close_product(request, cursor, product_id)

    if request.POST.get('delete'):
        delete_product(request, cursor, product_id)

    context = get_entire_bookmarket_with_user(request, cursor, True)
    return render(request, 'mypage/bookmarket.html', context)
# def backout (request):


def seek_detail(request):
    seek_id = request.POST['seek_id']

    cursor = connection.cursor()
    if request.POST.get('delete'):
        delete_seek(request, cursor, seek_id)

    context = get_entire_taxipool_with_user(request, cursor, True)
    return render(request, 'mypage/taxipool.html', context)

def attend_detail(request):
    attend_id = request.POST['attend_id']

    cursor = connection.cursor()
    if request.POST.get('delete'):
        delete_attend(request, cursor, attend_id)

    context = get_entire_taxipool_with_user(request, cursor, True)
    return render(request, 'mypage/taxipool.html', context)

def apply_detail(request):
    apply_id = request.POST['apply_id']
    content = request.POST['content']

    cursor = connection.cursor()
    if request.POST.get('change'):
        update_apply(request, cursor, apply_id, content)

    if request.POST.get('delete'):
        delete_apply(request, cursor, apply_id)

    context = get_entire_groupbuying_with_user(request, cursor, True)
    return render(request, 'mypage/groupbuying.html', context)

def open_detail(request):
    open_id = request.POST['open_id']
    cursor = connection.cursor()
    if request.POST.get('delete'):
        delete_open(request, cursor, open_id)

    context = get_entire_groupbuying_with_user(request, cursor, True)
    return render(request, 'mypage/groupbuying.html', context)

mypage/templates/mypage/mp_taxipool/attend_detail.html
<!-- 모달 : bid_cancel_user.html, 마이페이지 북마켓에서 유저가 bid 수정 혹은 취소용 -->
<form method="POST" action="{% url 'mypage:attend_detail' %}">
    {% csrf_token %}
    <div class="modal fade" id="attend_detail{{forloop.counter}}">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{ attend.departure }} <i class="fa fa-arrow-right" aria-hidden="true"></i> {{ attend.destination }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group row">
                        <label for="example-date-input" class="col-4 col-form-label">Depart Time</label>
                        <div class="col-8">
                            <input class="form-control"type="text" placeholder="{{ attend.depart_date }} {{ attend.depart_time }}" id="example-text-input" name="date" disabled>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="example-date-input" class="col-4 col-form-label">Recruited <i class="fa fa-users" aria-hidden="true"></i></label>
                        <div class="col-8">
                            <input class="form-control"type="text" placeholder="{{ attend.now_person }} / {{ attend.num_person }}" id="example-text-input" name="now_person" disabled>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="example-date-input" class="col-4 col-form-label">Content</label>
                        <div class="col-8">
                            <input class="form-control"type="text" placeholder="{{ attend.content }}" id="example-text-input" name="content" disabled>
                            <input class="form-control"type="hidden" name="attend_id" value="{{ attend.id }}" />
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    {% if attend.condition == "SEEKING" %}
                    <button type="button" class="btn btn-primary" value="1">Confirm</button>
                    <button type="submit" class="btn btn-danger"  name="delete" value="1">Delete</button>
                    {% else %}
                    <button type="button" class="btn btn-primary" value="1">Confirm</button>
                    <button type="submit" class="btn btn-danger"  name="delete" value="1">Delete</button>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</form>

mypage/templates/mypage/mp_taxipool/seek_detail.html
<!-- 모달 : bid_cancel_user.html, 마이페이지 북마켓에서 유저가 bid 수정 혹은 취소용 -->
<form method="POST" action="{% url 'mypage:seek_detail' %}">
    {% csrf_token %}
    <div class="modal fade" id="seek_detail{{forloop.counter}}">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{ seek.departure }} <i class="fa fa-arrow-right" aria-hidden="true"></i> {{ seek.destination }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group row">
                        <label for="example-date-input" class="col-4 col-form-label">Depart Time</label>
                        <div class="col-8">
                            <input class="form-control"type="text" placeholder="{{ seek.depart_date }} {{ seek.depart_time }}" id="example-text-input" name="date" disabled>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="example-date-input" class="col-4 col-form-label">Person</label>
                        <div class="col-8">
                            <input class="form-control"type="text" placeholder="{{ seek.now_person }} / {{ seek.num_person }}" id="example-text-input" name="now_person" disabled>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="example-date-input" class="col-4 col-form-label">Content</label>
                        <div class="col-8">
                            <input class="form-control"type="text" placeholder="{{ seek.content }}" id="example-text-input" name="content" disabled>
                            <input class="form-control"type="hidden" name="seek_id" value="{{ seek.id }}" />
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    {% if seek.condition == "SEEKING" %}
                    <button type="button" class="btn btn-primary" >Confirm</button>
                    <button type="submit" class="btn btn-danger"  name="delete" value="1">Delete</button>
                    {% else %}
                    <button type="button" class="btn btn-primary" disabled>Confirm</button>
                    <button type="submit" class="btn btn-danger"  name="delete" value="1"disabled>Delete</button>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</form>