groupbuying/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^open$', views.open_new, name='open_new'),
    url(r'^searching$', views.Searching, name='searching'),
    url(r'^applying$', views.applying, name='applying'),
]

home/urls.py
from django.conf.urls import url
from home import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

]

moau2/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from home import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', views.index, name = 'index'),
    url('', include('social_django.urls', namespace='social')),
    url(r'^home/', include('home.urls',  namespace='home')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^bookmarket/', include('bookmarket.urls', namespace='bookmarket')),
    url(r'^groupbuying/', include('groupbuying.urls', namespace='groupbuying')),
    url(r'^taxipool/', include('taxipool.urls', namespace='taxipool')),
    url(r'^mypage/', include('mypage.urls', namespace='mypage')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
   

groupbuying/models.py
from __future__ import unicode_literals
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.contrib.auth.models import User
from django.db import models
import datetime
import os



#http://hjh5488.tistory.com/12
def set_filename_format(now, instance, filename):
    """ file format setting
    e.g)
        {username}-{date}-{microsecond}{extension} hjh-2016-07-12-158859.png
    """
    return "{date}-{microsecond}{extension}".format(
        date=str(now.date()),
        microsecond=now.microsecond,
        extension=os.path.splitext(filename)[1],
    )

def user_directory_path(instance, filename):
    """
    image upload directory setting
    e.g)
        images/{year}/{month}/{day}/{username}/{filename}
        images/2016/7/12/hjh/hjh-2016-07-12-158859.png
    """
    now = datetime.datetime.now()
    path = "images/bookmarket/{filename}".format(
        filename=set_filename_format(now, instance, filename),
    )
    return path


class Party_Open(models.Model):
    #    category = models.CharField(max_length = 40, choices = CTCHOICE,default = ETC)
    RECRUITING = 'RE'
    SFAIL = 'SF'
    SSUCC = 'SS'
    SCANC = 'SC'
    CTCHOICE = (
        (RECRUITING, 'Recruiting'),
        (SFAIL, 'Sfail'),
        (SSUCC, 'Ssucc'),
        (SCANC, 'Scanc'),
    )
    title = models.CharField(max_length = 40)

    category = models.CharField(max_length = 40)
    content = models.CharField(max_length = 40)

    open_date = models.DateTimeField()
    num_person = models.IntegerField()
    now_person = models.IntegerField(default = 1)
    closing_date = models.DateTimeField()
    image = models.ImageField(upload_to=user_directory_path, default =0)
    condition = models.CharField(max_length =10, choices = CTCHOICE,default = RECRUITING)
    recruiter = models.ForeignKey(User, on_delete = models.CASCADE)
    def __str__(self):
        return self.title

class Apply_Applicant(models.Model):
    apply_date = models.DateTimeField()
    comment = models.CharField(max_length = 100)

    applicant = models.ForeignKey(User, on_delete=models.CASCADE)
    party = models.ForeignKey(Party_Open, on_delete=models.CASCADE)

groupbuying/forms.py
from django.forms import ModelForm
from .models import Party_Open

class RegisterForm(ModelForm):
    class Meta:
        model = Party_Open
        fields = ['category', 'content', 'open_date', 'closing_date', 'num_person', 'image','condition']

groupbuying/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required
from django.db import connection, transaction
from home.views import * # common fucntion
from django.contrib import messages # error
import datetime

# Create your views here.
from django.utils import timezone
import datetime

# Create your views here.
def index(request):
    cursor = connection.cursor()
    cursor.execute("SELECT * FROM groupbuying_party_open")
    row = dictfetchall(cursor)
    context = {"row": row}
    return render(request, 'groupbuying/index.html', context)

def open_new(request):
    if request.method == "POST":
        new_party = Party_Open(
                category = request.POST['category'],
                title = request.POST['title'],
                num_person = request.POST['num_person'],
                content = request.POST['content'],
                closing_date = request.POST['closing_date'],
                image = request.FILES['image'],
                )
        new_party.recruiter = request.user
        new_party.open_date = str(datetime.datetime.now())
        if new_party.open_date > new_party.closing_date:
            messages.error(request, "Date error : Before today.")
            return render (request, 'groupbuying/index.html')
        else :
            new_party.condition = 'RECRUITING'
            new_party.save()
            return redirect('groupbuying:index')
    else:
        form = RegisterForm()
    return render(request, 'groupbuying/index.html', {'form': form})

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]
    
def Searching(request) :
        cursor = connection.cursor()
        selected_category =request.POST['selected_category']
        selected_titl =request.POST['selected_title']
        cursor.execute("SELECT * FROM groupbuying_party_open WHERE category = %s AND title LIKE %s",[selected_category,'%'+selected_titl+'%'] )
        row = dictfetchall(cursor)

        context = {"row":row, "selected_category":selected_category}
        return render(request, 'groupbuying/index.html', context)


@login_required()
def applying(request):
    cursor1 = connection.cursor()
    get_entire_groupbuying_with_user(request, cursor1, True)
    if request.POST['condition1'] == "RECRUITING":
        apply_date = datetime.datetime.now()
        comment1 = request.POST['comment']
        party = Party_Open.objects.get(id=request.POST['party_id'])
        num_person1 = request.POST['num_person']
        now_person1 = request.POST['now_person']

        applicant = request.user
        cursor = connection.cursor()
        if num_person1 <= now_person1 :
            messages.error(request, "People number error : It's FULL!")
            return render (request, 'groupbuying/index.html')

        cursor.execute("INSERT INTO groupbuying_apply_applicant(apply_date, comment, party_id, applicant_id) VALUES (%s, %s, %s, %s)", [apply_date, comment1, party.id, applicant.id])

        cursor.execute("UPDATE groupbuying_party_open SET now_person = now_person+1 WHERE id = %s", [party.id])

        cursor.execute("SELECT * FROM groupbuying_party_open")
        row = dictfetchall(cursor)
        context = {"row": row}
        return render(request, 'groupbuying/index.html', context)
    else :
        cursor = connection.cursor()
        cursor.execute("SELECT * FROM groupbuying_party_open")

        row = dictfetchall(cursor)
        context = {"row": row}
        return render(request, 'groupbuying/index.html', context)

groupbuying/templates/groupbuying/modals/details.html
<form method="POST" action="{% url 'groupbuying:applying' %}">
    {% csrf_token %}
    <div class="modal fade" id="details{{forloop.counter}}">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{ prod.title }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td>Gathered</td>
                        <td>{{ prod.now_person }}</td>
                      </tr>
                      <tr>
                        <td>Gathering</td>
                        <td>{{ prod.num_person }}</td>
                      </tr>
                      <tr>
                        <td>Due data</td>
                        <td>{{ prod.closing_date|date:"d/M/Y" }}</td>
                      </tr>

                      <tr>
                        <td>Content </td>
                        <td>{{ prod.content }}</td>
                      </tr>

                      <tr>
                        <td>Comment><td><textarea class="form-control" rows="3" id="comment" name = "comment"></textarea>
                          <input class="form-control" type="hidden" name="party_id" value="{{ prod.id }}">
                          <input class="form-control" type="hidden" name="now_person" value="{{ prod.now_person }}">
                          <input class="form-control" type="hidden" name="num_person" value="{{ prod.num_person }}">
                          <input class="form-control" type="hidden" name="condition1" value="{{ prod.condition }}">
                          </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Apply</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancle</button>
                </div>
            </div>
        </div>
    </div>
</form>

groupbuying/templates/groupbuying/modals/open.html
<form method="POST" action="{% url 'groupbuying:open_new' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="modal fade" id="open">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Open your Party</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group row">
                        <label for="example-text-input" class="col-4 col-form-label">Category <small>(sellcet)</small></label>
                        <div class="col-8">
                            <select class="form-control" id="exampleSelect1" name="category">
                                <option value="Delivery">Delivery</option>
                                <option value="Cosmetic">Cosmetic</option>
                                <option value="Electronic">Electronic</option>
                                <option value="ETC">ETC</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="example-text-input" class="col-4 col-form-label">Title</label>
                        <div class="col-8">
                            <input class="form-control" type="text" placeholder="Chicken / Pizza ... " id="example-text-input" name="title">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="example-text-input" class="col-4 col-form-label">Recruiting P.N</label>
                        <div class="col-8">
                            <input class="form-control" type="text" placeholder="Limitation of recruitment members" id="example-text-input" name="num_person">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="example-date-input" class="col-4 col-form-label">Due Date</label>
                        <div class="col-8">
                            <input class="form-control" type="date" value="{% now "Y-m-d" %}" id="example-date-input" name="closing_date">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="example-text-input" class="col-4 col-form-label">Content</label>
                        <div class="col-12">
                            <textarea class="form-control" placeholder="What you want to say detail about group purchasing" id="example-textarea-input" name="content" rows="5"></textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="example-text-input" class="col-4 col-form-label">Image</label>
                        <div class="col-8">
                            <input type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp" name="image">
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Open</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</form>