home/urls.py
from django.conf.urls import url
from home import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

]

moau2/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from home import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', views.index, name = 'index'),
    url('', include('social_django.urls', namespace='social')),
    url(r'^home/', include('home.urls',  namespace='home')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^bookmarket/', include('bookmarket.urls', namespace='bookmarket')),
    url(r'^groupbuying/', include('groupbuying.urls', namespace='groupbuying')),
    url(r'^taxipool/', include('taxipool.urls', namespace='taxipool')),
    url(r'^mypage/', include('mypage.urls', namespace='mypage')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
   

taxipool/urls.py
from django.conf.urls import include, url
from . import views
urlpatterns = [
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.index, name='index'),
    url(r'^seek$', views.seek_new, name='seek_new'),
    url(r'^searching$', views.Searching, name='Searching'),
    url(r'^attending$', views.attending, name='attending'),
]

taxipool/models.py
from __future__ import unicode_literals
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.contrib.auth.models import User
from django.db import models

import datetime
import os


class Seek_Taxi(models.Model):

    SEEKING = 'SE1'
    SFAIL = 'SF1'
    SSUCC = 'SS1'
    SCANC = 'SC1'
    CTCHOICE = (
        (SEEKING, 'Seeking'),
        (SFAIL, 'Sefail'),
        (SSUCC, 'Sesucc'),
        (SCANC, 'Secanc'),
    )
    departure = models.CharField(max_length = 40)
    destination = models.CharField(max_length = 40)
    depart_date = models.DateField()
    depart_time = models.TimeField()
    num_person = models.IntegerField(max_length = 4)
    now_person = models.IntegerField(default = 1)
    content = models.CharField(max_length = 100)
    condition = models.CharField(max_length = 10, choices = CTCHOICE,default = SEEKING)
    seeker = models.ForeignKey(User, on_delete = models.CASCADE)
    def __str__(self):
        return self.departure + " / " + self.destination

class Attend_Passenger(models.Model):
    attend_date = models.DateTimeField()
    comment = models.CharField(max_length = 100)

    taxi = models.ForeignKey(Seek_Taxi, on_delete=models.CASCADE)
    passenger = models.ForeignKey(User, on_delete=models.CASCADE)

taxipool/forms.py
from django.forms import ModelForm
from .models import Seek_Taxi

class RegisterForm(ModelForm):
    class Meta:
        model = Seek_Taxi
        fields = ['departure', 'destination', 'depart_date', 'depart_time',
        'num_person', 'content', 'condition']

taxipool/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required
from django.db import connection, transaction
from django.contrib import messages # error
import datetime
from home.views import *
# Create your views here.
from django.utils import timezone
import datetime

def index(request):
    cursor = connection.cursor()
    cursor.execute("SELECT * FROM taxipool_seek_taxi")
    row = dictfetchall(cursor)
    context = {"row": row}
    return render(request, 'taxipool/index.html', context)

def seek_new(request):
    if request.method == "POST":
        new_taxi = Seek_Taxi(
            content = request.POST['content'],
            num_person = request.POST['num_person'],
            destination = request.POST['destination'],
            departure = request.POST['departure'],
            depart_date = request.POST['depart_date'],
            depart_time = request.POST['depart_time'],
        )
        new_taxi.seeker = request.user
        if new_taxi.num_person > "4" :
            messages.error(request, "People number error : Maximum is 4.")
            return render (request, 'taxipool/index.html')
        register_date = datetime.date.today()
        if str(register_date) > new_taxi.depart_date  :
            messages.error(request, "Date error : Before today.")
            return render (request, 'taxipool/index.html')
        else :
            new_taxi.condition = 'SEEKING'
            new_taxi.save()
            return redirect('taxipool:index')


    else:
        form = RegisterForm()
    return render(request, 'taxipool/index.html', {'form': form})



def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]
def Searching(request) :
        cursor = connection.cursor()
        selected_category =request.POST['selected_category']
        selected_titl = request.POST['selected_title']
        cursor.execute("SELECT * FROM taxipool_seek_taxi WHERE ('Destination' = %s AND destination LIKE %s) OR ('departure' = %s AND departure LIKE %s)",[selected_category,'%'+selected_titl+'%',selected_category,'%'+selected_titl+'%'] )
        row = dictfetchall(cursor)#

        context = {"row":row, "selected_category":selected_category}
        return render(request, 'taxipool/index.html', context)




@login_required()
def attending(request):
    cursor1 = connection.cursor()
    get_entire_taxipool_with_user(request, cursor1, True)
    if request.POST['condition1'] == "SEEKING":
        attend_date = datetime.datetime.now()
        comment1 = request.POST['comment']
        taxi = Seek_Taxi.objects.get(id=request.POST['taxi_id'])
        num_person1 = request.POST['num_person']
        now_person1 = request.POST['now_person']

        passenger = request.user
        cursor = connection.cursor()
        if num_person1 <= now_person1 :
            messages.error(request, "People number error :It's FULL!")
            return render (request, 'taxipool/index.html')
        cursor.execute("INSERT INTO taxipool_attend_passenger(attend_date, comment, taxi_id, passenger_id) VALUES (%s, %s, %s, %s)", [attend_date, comment1, taxi.id, passenger.id])

        cursor.execute("UPDATE taxipool_seek_taxi SET now_person = now_person+1 WHERE id = %s", [taxi.id])

        cursor.execute("SELECT * FROM taxipool_seek_taxi")
        row = dictfetchall(cursor)
        context = {"row": row}
        return render(request, 'taxipool/index.html', context)
    else :
        cursor = connection.cursor()
        cursor.execute("SELECT * FROM taxipool_seek_taxi")

        row = dictfetchall(cursor)
        context = {"row": row}
        return render(request, 'taxipool/index.html', context)

taxipool/templates/taxipool/modals/details.html
<form method="POST" action="{% url 'taxipool:attending' %}">
    {% csrf_token %}
    <div class="modal fade" id="details{{forloop.counter}}">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{ prod.departure }}->{{prod.destination}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body row">
                  <table class="table table-user-information col-sm-10 offset-1">
                    <tbody>
                      <tr>
                        <td>Gathered</td>
                        <td>{{ prod.now_person }}</td>
                      </tr>
                      <tr>
                        <td>Gathering</td>
                        <td>{{ prod.num_person }}</td>
                      </tr>
                      <tr>
                        <td>Due dateTime</td>
                        <td>{{ro.depart_date|date:"d/M/Y" }}&nbsp;&nbsp;{{ro.depart_time|time:"G" }}:{{ro.depart_time|time:"i" }}</td>
                      </tr>

                      <tr>
                        <td>Content </td>
                        <td>{{ prod.content }}</td>
                      </tr>
                      
                      <tr>
                        <td>Comment</td>
                        <td><textarea class="form-control" id="example-textarea-input" name="comment" rows="3"></textarea></td>
                        <td><input class="form-control" type="hidden" name="taxi_id" value="{{ prod.id }}"></td>
                        <td><input class="form-control" type="hidden" name="now_person" value="{{ prod.now_person }}"></td>
                        <td><input class="form-control" type="hidden" name="num_person" value="{{ prod.num_person }}"></td>
                        <td><input class="form-control" type="hidden" name="condition1" value="{{ prod.condition }}"></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Seek</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</form>

taxipool/templates/taxipool/modals/seek.html
<form method="POST" action="{% url 'taxipool:seek_new' %}">
    {% csrf_token %}
    <div class="modal fade" id="seek">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Seek your Taxi Members</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group row">
                        <label for="example-text-input" class="col-4 col-form-label">Departure</label>
                        <div class="col-8">
                            <input class="form-control" type="text" placeholder="UNIST, Ulsan station..." id="example-text-input" name="departure">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="example-text-input" class="col-4 col-form-label">Destination</label>
                        <div class="col-8">
                            <input class="form-control" type="text" placeholder="Ulsan Univ, Gu-young ri..." id="example-text-input" name="destination">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="example-date-input" class="col-4 col-form-label">Depart Date</label>
                        <div class="col-8">
                            <input class="form-control" type="date" value="{% now "Y-m-d" %}" id="example-date-input" name="depart_date">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="example-date-input" class="col-4 col-form-label">Depart Time</label>
                        <div class="col-8">
                            <input class="form-control" type="time" value="{% now "G-i" %}" id="example-time-input" name="depart_time">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="example-text-input" class="col-4 col-form-label">Recruiting P.N<br>(Up to 4)</label>
                        <div class="col-8">
                            <input class="form-control" type="text" placeholder="Limitation of taxi sharing members" id="example-text-input" name="num_person">
                        </div>
                    </div>
                    <div class="form-group row">
                      <label for="example-text-input" class="col-4 col-form-label">Content</label>
                      <div class="col-12">
                          <textarea class="form-control" placeholder="Any comment you want to mention briefly" id="example-textarea-input" name="content" rows="5"></textarea>
                      </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Seek</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</form>