groupbuying/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^open$', views.open_new, name='open_new'),
    url(r'^searching$', views.Searching, name='searching'),
    url(r'^applying$', views.applying, name='applying'),
]

home/urls.py
from django.conf.urls import url
from home import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

]

moau2/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from home import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', views.index, name = 'index'),
    url('', include('social_django.urls', namespace='social')),
    url(r'^home/', include('home.urls',  namespace='home')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^bookmarket/', include('bookmarket.urls', namespace='bookmarket')),
    url(r'^groupbuying/', include('groupbuying.urls', namespace='groupbuying')),
    url(r'^taxipool/', include('taxipool.urls', namespace='taxipool')),
    url(r'^mypage/', include('mypage.urls', namespace='mypage')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
   

groupbuying/models.py
from __future__ import unicode_literals
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.contrib.auth.models import User
from django.db import models
import datetime
import os



#http://hjh5488.tistory.com/12
def set_filename_format(now, instance, filename):
    """ file format setting
    e.g)
        {username}-{date}-{microsecond}{extension} hjh-2016-07-12-158859.png
    """
    return "{date}-{microsecond}{extension}".format(
        date=str(now.date()),
        microsecond=now.microsecond,
        extension=os.path.splitext(filename)[1],
    )

def user_directory_path(instance, filename):
    """
    image upload directory setting
    e.g)
        images/{year}/{month}/{day}/{username}/{filename}
        images/2016/7/12/hjh/hjh-2016-07-12-158859.png
    """
    now = datetime.datetime.now()
    path = "images/bookmarket/{filename}".format(
        filename=set_filename_format(now, instance, filename),
    )
    return path


class Party_Open(models.Model):
    #    category = models.CharField(max_length = 40, choices = CTCHOICE,default = ETC)
    RECRUITING = 'RE'
    SFAIL = 'SF'
    SSUCC = 'SS'
    SCANC = 'SC'
    CTCHOICE = (
        (RECRUITING, 'Recruiting'),
        (SFAIL, 'Sfail'),
        (SSUCC, 'Ssucc'),
        (SCANC, 'Scanc'),
    )
    title = models.CharField(max_length = 40)

    category = models.CharField(max_length = 40)
    content = models.CharField(max_length = 40)

    open_date = models.DateTimeField()
    num_person = models.IntegerField()
    now_person = models.IntegerField(default = 1)
    closing_date = models.DateTimeField()
    image = models.ImageField(upload_to=user_directory_path, default =0)
    condition = models.CharField(max_length =10, choices = CTCHOICE,default = RECRUITING)
    recruiter = models.ForeignKey(User, on_delete = models.CASCADE)
    def __str__(self):
        return self.title

class Apply_Applicant(models.Model):
    apply_date = models.DateTimeField()
    comment = models.CharField(max_length = 100)

    applicant = models.ForeignKey(User, on_delete=models.CASCADE)
    party = models.ForeignKey(Party_Open, on_delete=models.CASCADE)

groupbuying/forms.py
from django.forms import ModelForm
from .models import Party_Open

class RegisterForm(ModelForm):
    class Meta:
        model = Party_Open
        fields = ['category', 'content', 'open_date', 'closing_date', 'num_person', 'image','condition']

groupbuying/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required
from django.db import connection, transaction
from home.views import * # common fucntion
from django.contrib import messages # error
import datetime

# Create your views here.
from django.utils import timezone
import datetime

# Create your views here.
def index(request):
    cursor = connection.cursor()
    cursor.execute("SELECT * FROM groupbuying_party_open")
    row = dictfetchall(cursor)
    context = {"row": row}
    return render(request, 'groupbuying/index.html', context)

def open_new(request):
    if request.method == "POST":
        new_party = Party_Open(
                category = request.POST['category'],
                title = request.POST['title'],
                num_person = request.POST['num_person'],
                content = request.POST['content'],
                closing_date = request.POST['closing_date'],
                image = request.FILES['image'],
                )
        new_party.recruiter = request.user
        new_party.open_date = str(datetime.datetime.now())
        if new_party.open_date > new_party.closing_date:
            messages.error(request, "Date error : Before today.")
            return render (request, 'groupbuying/index.html')
        else :
            new_party.condition = 'RECRUITING'
            new_party.save()
            return redirect('groupbuying:index')
    else:
        form = RegisterForm()
    return render(request, 'groupbuying/index.html', {'form': form})

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]
    
def Searching(request) :
        cursor = connection.cursor()
        selected_category =request.POST['selected_category']
        selected_titl =request.POST['selected_title']
        cursor.execute("SELECT * FROM groupbuying_party_open WHERE category = %s AND title LIKE %s",[selected_category,'%'+selected_titl+'%'] )
        row = dictfetchall(cursor)

        context = {"row":row, "selected_category":selected_category}
        return render(request, 'groupbuying/index.html', context)


@login_required()
def applying(request):
    cursor1 = connection.cursor()
    get_entire_groupbuying_with_user(request, cursor1, True)
    if request.POST['condition1'] == "RECRUITING":
        apply_date = datetime.datetime.now()
        comment1 = request.POST['comment']
        party = Party_Open.objects.get(id=request.POST['party_id'])
        num_person1 = request.POST['num_person']
        now_person1 = request.POST['now_person']

        applicant = request.user
        cursor = connection.cursor()
        if num_person1 <= now_person1 :
            messages.error(request, "People number error : It's FULL!")
            return render (request, 'groupbuying/index.html')

        cursor.execute("INSERT INTO groupbuying_apply_applicant(apply_date, comment, party_id, applicant_id) VALUES (%s, %s, %s, %s)", [apply_date, comment1, party.id, applicant.id])

        cursor.execute("UPDATE groupbuying_party_open SET now_person = now_person+1 WHERE id = %s", [party.id])

        cursor.execute("SELECT * FROM groupbuying_party_open")
        row = dictfetchall(cursor)
        context = {"row": row}
        return render(request, 'groupbuying/index.html', context)
    else :
        cursor = connection.cursor()
        cursor.execute("SELECT * FROM groupbuying_party_open")

        row = dictfetchall(cursor)
        context = {"row": row}
        return render(request, 'groupbuying/index.html', context)

groupbuying/templates/groupbuying/index.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content %}
</div>
<div class="jumbotron jumbo_group">
    <div class="container">
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <strong>{{ message }}</strong>
            </div>
            {% endfor %}
        {% endif %}
        <form method="POST" action="{% url 'groupbuying:searching' %}">
            <div class="row justify-content-md-center"> <!-- for search box -->
            {% csrf_token %}
                <div class="col-md-2">
                    <select class="form-control input-lg mb-2 mr-sm-2 mb-sm-0" name="selected_category" style="height: 100%;">
                        <option selected value="Delivery">Delivery</option>
                        <option value="Cosmetic">Cosmetic</option>
                        <option value="Electronic">Electronic</option>
                        <option value="ETC">ETC</option>
                    </select>
                </div>
                <div class="col-md-7">
                    <div class="input-group input-group-lg">
                        <input type="text" class="form-control" placeholder="EX) Pizza / Chicken ..." name="selected_title" />
                        <div class="input-group-btn">
                            <div class="btn-group" role="group">
                                <button type="submmit" class="btn btn-primary btn-lg"><i class="fa fa-search" aria-hidden="true"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <div class="row justify-content-md-center"> 
            <div class="col-md-12 next_search">
                <form class="form-inline">
                    <div class="form-group">
                        <label><h2 class="text-uppercase" style="color:#fff"> <strong>Open your Party</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h2></label>
                        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="{% if user.is_authenticated %}#open{% else %}#alarm_login{% endif %}">Open</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

        {% include 'groupbuying/modals/open.html' %}
        {% include 'modals/alarm_login.html' %}

<div class="container">
    {% include 'groupbuying/partials/image_card.html' %}
</div>
{% endblock content %}